export const conditions = [
  { code: 0, description: 'Clear sky' },
  { code: 1, description: 'Mainly clear' },
  { code: 2, description: 'Partly cloudy' },
  { code: 3, description: 'Cloudy' },
  { code: 45, description: 'Foggy' },
  { code: 48, description: 'Heavy fog' },
  { code: 51, description: 'Light drizzle' },
  { code: 53, description: 'Moderate drizzle' },
  { code: 55, description: 'Drizzle' },
  { code: 56, description: ' Light freezing drizzle' },
  { code: 57, description: 'Freezing drizzle' },
  { code: 61, description: 'Slight rain' },
  { code: 63, description: 'Moderate  rain' },
  { code: 65, description: 'Heavy rain' },
  { code: 66, description: 'Light freezing rain' },
  { code: 67, description: 'Heavy freezing Rain' },
  { code: 71, description: 'Slight snow fall' },
  { code: 73, description: 'Moderate snow fall' },
  { code: 75, description: 'Heavy intensity snow fall' },
  { code: 77, description: 'Snow grains' },
  { code: 80, description: 'Slight rain showers' },
  { code: 81, description: 'Moderate rain showers' },
  { code: 82, description: 'Violent rain showers' },
  { code: 85, description: 'Slight snow showers' },
  { code: 86, description: 'Heavy snow showers' },
  { code: 95, description: 'Thunderstorm' },
  { code: 96, description: 'Thunderstorm with slight hail' },
  { code: 99, description: 'Thunderstorm with heavy hail' },
];
