import daySun from '../images/conditions/day-sun-min.png';
import dayClouds from '../images/conditions/day-clouds-min.png';
import dayRain from '../images/conditions/day-rain-min.png';
import daySnow from '../images/conditions/day-snow-min.png';
import dayStorm from '../images/conditions/day-storm-min.png';
import dayWind from '../images/conditions/day-wind-min.png';

import nightMoon from '../images/conditions/night-moon-min.png';
import nightClouds from '../images/conditions/night-clouds-min.png';
import nightRain from '../images/conditions/night-rain-min.png';
import nightWind from '../images/conditions/night-wind-min.png';
import nightSnow from '../images/conditions/night-snow-min.png';
import nightStorm from '../images/conditions/night-storm-min.png';

export const conditionsWeatherApi = [
  {
    code: 1000,
    day: 'Sunny',
    night: 'Clear',
    icon: 113,
    png: [daySun, nightMoon],
  },
  {
    code: 1003,
    day: 'Partly cloudy',
    night: 'Partly cloudy',
    icon: 116,
    png: [dayClouds, nightClouds],
  },
  {
    code: 1006,
    day: 'Cloudy',
    night: 'Cloudy',
    icon: 119,
    png: [dayClouds, nightClouds],
  },
  {
    code: 1009,
    day: 'Overcast',
    night: 'Overcast',
    icon: 122,
    png: [dayClouds, nightClouds],
  },
  {
    code: 1030,
    day: 'Mist',
    night: 'Mist',
    icon: 143,
    png: [dayWind, nightWind],
  },
  {
    code: 1063,
    day: 'Patchy rain possible',
    night: 'Patchy rain possible',
    icon: 176,
    png: [dayRain, nightRain],
  },
  {
    code: 1066,
    day: 'Patchy snow possible',
    night: 'Patchy snow possible',
    icon: 179,
    png: [daySnow, nightSnow],
  },
  {
    code: 1069,
    day: 'Patchy sleet possible',
    night: 'Patchy sleet possible',
    icon: 182,
    png: [daySnow, nightSnow],
  },
  {
    code: 1072,
    day: 'Patchy freezing drizzle possible',
    night: 'Patchy freezing drizzle possible',
    icon: 185,
    png: [dayRain, nightRain],
  },
  {
    code: 1087,
    day: 'Thundery outbreaks possible',
    night: 'Thundery outbreaks possible',
    icon: 200,
    png: [dayStorm, nightStorm],
  },
  {
    code: 1114,
    day: 'Blowing snow',
    night: 'Blowing snow',
    icon: 227,
    png: [daySnow, nightSnow],
  },
  {
    code: 1117,
    day: 'Blizzard',
    night: 'Blizzard',
    icon: 230,
    png: [daySnow, nightSnow],
  },
  {
    code: 1135,
    day: 'Fog',
    night: 'Fog',
    icon: 248,
    png: [dayWind, nightWind],
  },
  {
    code: 1147,
    day: 'Freezing fog',
    night: 'Freezing fog',
    icon: 260,
    png: [dayWind, nightWind],
  },
  {
    code: 1150,
    day: 'Patchy light drizzle',
    night: 'Patchy light drizzle',
    icon: 263,
    png: [dayRain, nightRain],
  },
  {
    code: 1153,
    day: 'Light drizzle',
    night: 'Light drizzle',
    icon: 266,
    png: [dayRain, nightRain],
  },
  {
    code: 1168,
    day: 'Freezing drizzle',
    night: 'Freezing drizzle',
    icon: 281,
    png: [dayRain, nightRain],
  },
  {
    code: 1171,
    day: 'Heavy freezing drizzle',
    night: 'Heavy freezing drizzle',
    icon: 284,
    png: [dayRain, nightRain],
  },
  {
    code: 1180,
    day: 'Patchy light rain',
    night: 'Patchy light rain',
    icon: 293,
    png: [dayRain, nightRain],
  },
  {
    code: 1183,
    day: 'Light rain',
    night: 'Light rain',
    icon: 296,
    png: [dayRain, nightRain],
  },
  {
    code: 1186,
    day: 'Moderate rain at times',
    night: 'Moderate rain at times',
    icon: 299,
    png: [dayRain, nightRain],
  },
  {
    code: 1189,
    day: 'Moderate rain',
    night: 'Moderate rain',
    icon: 302,
    png: [dayRain, nightRain],
  },
  {
    code: 1192,
    day: 'Heavy rain at times',
    night: 'Heavy rain at times',
    icon: 305,
    png: [dayRain, nightRain],
  },
  {
    code: 1195,
    day: 'Heavy rain',
    night: 'Heavy rain',
    icon: 308,
    png: [dayRain, nightRain],
  },
  {
    code: 1198,
    day: 'Light freezing rain',
    night: 'Light freezing rain',
    icon: 311,
    png: [dayRain, nightRain],
  },
  {
    code: 1201,
    day: 'Moderate or heavy freezing rain',
    night: 'Moderate or heavy freezing rain',
    icon: 314,
    png: [dayRain, nightRain],
  },
  {
    code: 1204,
    day: 'Light sleet',
    night: 'Light sleet',
    icon: 317,
    png: [daySnow, nightSnow],
  },
  {
    code: 1207,
    day: 'Moderate or heavy sleet',
    night: 'Moderate or heavy sleet',
    icon: 320,
    png: [daySnow, nightSnow],
  },
  {
    code: 1210,
    day: 'Patchy light snow',
    night: 'Patchy light snow',
    icon: 323,
    png: [daySnow, nightSnow],
  },
  {
    code: 1213,
    day: 'Light snow',
    night: 'Light snow',
    icon: 326,
    png: [daySnow, nightSnow],
  },
  {
    code: 1216,
    day: 'Patchy moderate snow',
    night: 'Patchy moderate snow',
    icon: 329,
    png: [daySnow, nightSnow],
  },
  {
    code: 1219,
    day: 'Moderate snow',
    night: 'Moderate snow',
    icon: 332,
    png: [daySnow, nightSnow],
  },
  {
    code: 1222,
    day: 'Patchy heavy snow',
    night: 'Patchy heavy snow',
    icon: 335,
    png: [daySnow, nightSnow],
  },
  {
    code: 1225,
    day: 'Heavy snow',
    night: 'Heavy snow',
    icon: 338,
    png: [daySnow, nightSnow],
  },
  {
    code: 1237,
    day: 'Ice pellets',
    night: 'Ice pellets',
    icon: 350,
    png: [daySnow, nightSnow],
  },
  {
    code: 1240,
    day: 'Light rain shower',
    night: 'Light rain shower',
    icon: 353,
    png: [dayRain, nightRain],
  },
  {
    code: 1243,
    day: 'Moderate or heavy rain shower',
    night: 'Moderate or heavy rain shower',
    icon: 356,
    png: [dayRain, nightRain],
  },
  {
    code: 1246,
    day: 'Torrential rain shower',
    night: 'Torrential rain shower',
    icon: 359,
    png: [dayRain, nightRain],
  },
  {
    code: 1249,
    day: 'Light sleet showers',
    night: 'Light sleet showers',
    icon: 362,
    png: [daySnow, nightSnow],
  },
  {
    code: 1252,
    day: 'Moderate or heavy sleet showers',
    night: 'Moderate or heavy sleet showers',
    icon: 365,
    png: [daySnow, nightSnow],
  },
  {
    code: 1255,
    day: 'Light snow showers',
    night: 'Light snow showers',
    icon: 368,
    png: [daySnow, nightSnow],
  },
  {
    code: 1258,
    day: 'Moderate or heavy snow showers',
    night: 'Moderate or heavy snow showers',
    icon: 371,
    png: [daySnow, nightSnow],
  },
  {
    code: 1261,
    day: 'Light showers of ice pellets',
    night: 'Light showers of ice pellets',
    icon: 374,
    png: [daySnow, nightSnow],
  },
  {
    code: 1264,
    day: 'Moderate or heavy showers of ice pellets',
    night: 'Moderate or heavy showers of ice pellets',
    icon: 377,
    png: [daySnow, nightSnow],
  },
  {
    code: 1273,
    day: 'Patchy light rain with thunder',
    night: 'Patchy light rain with thunder',
    icon: 386,
    png: [dayStorm, nightStorm],
  },
  {
    code: 1276,
    day: 'Moderate or heavy rain with thunder',
    night: 'Moderate or heavy rain with thunder',
    icon: 389,
    png: [dayStorm, nightStorm],
  },
  {
    code: 1279,
    day: 'Patchy light snow with thunder',
    night: 'Patchy light snow with thunder',
    icon: 392,
    png: [dayStorm, nightStorm],
  },
  {
    code: 1282,
    day: 'Moderate or heavy snow with thunder',
    night: 'Moderate or heavy snow with thunder',
    icon: 395,
    png: [dayStorm, nightStorm],
  },
];
